fixes:
  - "ballerina/http/*/::../ballerina/"

ignore:
  - "ballerina-tests"
  - "compiler-plugin-tests"
  - "native/src/main/java/io/ballerina/stdlib/http/api/testutils"

coverage:
  precision: 2
  round: down
  range: "60...80"
  status:
    project:
      default:
        target: 80
 